### ISSUE TITLE
New mail doesn't appear in the list

### ISSUE THREAD

**Issue by eoli3n** [runbox/runbox7#912] opened 2021-02-19 17:15 UTC
I just received a new mail, you can see "1" on "Inbox", but the list isn't refreshed properly.

![Swappshot Fri Feb 19 18:12:07 2021](https://user-images.githubusercontent.com/14223657/108537610-1bd23800-72de-11eb-83a3-5da1ab1c1513.png)

Then, if i move to "Sent" folder and come back "Inbox", it appears : 18h09 "**N**..."

![Swappshot Fri Feb 19 18:12:20 2021](https://user-images.githubusercontent.com/14223657/108537615-1c6ace80-72de-11eb-8904-2680865a0940.png)

Possibly related to https://github.com/runbox/runbox7/issues/907

**Comment by eoli3n** [comment] 2021-12-22 11:49
Still having that issue, pretty annoying, I keeps refreshing the whole page to get new mails.

**Comment by gtandersen** [comment] 2022-01-06 15:40
I have experienced this issue as well. Could be related to #694.

**Comment by gtandersen** [comment] 2022-01-23 17:27
See also #917 and #926.

**Comment by gtandersen** [comment] 2022-01-23 17:30
Note that the local index does not appear to be used here.

**Comment by castaway** [comment] 2022-01-24 12:08
I can't reproduce this:
1) turn off index sync
2) scroll to top of inbox
3) mark all as read just in case
4) send email from elsewhere to my runbox account
5) twiddle thumbs
6) email appears both in folder counts and at top of inbox


Could you verify these steps cause things not to work for you? Also could you please see if the devtools console logging says anything in red (or indicates any sort of fail)

**Comment by gtandersen** [comment] 2022-10-13 14:13
This seems to happen in Safari from time to time, but not seen in Firefox.

**Comment by gtandersen** [comment] 2023-10-09 14:56
Couldn't reproduce this in Safari with local index off; closing issue.

**Closed by gtandersen** 2023-10-09 14:56 UTC
Labels: bug, status-waiting for response, status-can't reproduce, P-high
