### ISSUE TITLE
"reply to" address for Other Identities is ignored and the main username is sent as the "reply to" address

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#663] opened 2020-07-09 08:55 UTC
As per the subject. "reply to" address for Other Identities is ignored and the main username is sent as the "reply to" address instead.

**Comment by castaway** [comment] 2020-07-09 09:13
.. and it seems sending from an Alias with a "reply-to" field on it, doesnt send the Reply-To email header at all.

**Comment by castaway** [comment] 2020-07-09 11:14
I also tested sending from an identity-with-reply-to on RMM6, the email dropped into my "sent mail" but didnt actually arrive at its destination..

**Comment by castaway** [comment] 2020-07-13 08:56
@hernan604 made a patch for the backend.

Testing with it this morning: 

* The email from an external identity I just set, does have a "reply-to" header when I view it in Sent mail (however the email itself hasnt arrived). 

* The alias I tried (Identities setup allows me to set a reply-to value there as well) - doesn't have one in Sent email, nor did that arrive :(

**Comment by castaway** [comment] 2020-07-27 11:12
Current status: @davidbowdley confirmed that **aliases** in runbox7 are / should be the same as **identities** where sending email is concerned, therefore any "reply-to" set on them should do the correct thing.

From usage/code it looks like aliases map directly to rmm6 aliases ("Add Alias" on the Identities screen actually sends me to the RMM6 alias page), the Edit button (RMM7) then lets me add a reply-to on it - I haven't looked into how these are stored.

This last is presumably whats causing the issue - code added to the backend "send_msg" explicitly disallows using reply-to with aliases in RMM6 (see gitlab issue 598), so therefore it doesn't work with RMM7 alias/identities either. As far as I can see we're going to need to separate rmm7/rmm6 aliases more.. or at least come up with a way to determine which UI sent the email, to allow reply-to on aliases from RMM7 .

Thoughts: @gtandersen , @hernan604 ?

**Comment by gtandersen** [comment] 2021-09-29 20:50
It still appears that messages from aliases with a custom reply-to are not actually sent, although the message appears in the Sent folder.

This can be reproduced in the "test" account with the "blackhole" identity.

**Comment by castaway** [comment] 2021-10-04 11:48
After various testing - existing aliases of mine on prod with reply-to - emails sent don't arrive (but go to Sent folder), same for a new alias with reply-to on prod. It seems to work however for @runboxdave on prod, and for me on my dev install (with both old and new aliases).

Not entirely sure how to continue debugging this, may need someone to look in the server logs.

**Comment by castaway** [comment] 2021-10-05 10:53
Update: Found them! Mine from prod with alias+reply_to landed in gmails Spam folder (which isnt visible over IMAP inbox, and that's where I was looking..)

**Comment by castaway** [comment] 2021-10-06 11:16
This doesnt seem to be a problem right now, closing.

**Closed by castaway** 2021-10-06 11:16 UTC
Labels: bug, P-urgent
