### ISSUE TITLE
adding folder causes all folders to disappear

### ISSUE THREAD

**Issue by deutrino** [runbox/runbox7#314] opened 2019-09-27 18:32 UTC
I attempted to create a folder from the "+" icon in the left side pane in Runbox 7 and it failed without generating any error. I then created the folder in Runbox 6 and now Runbox 7 displays no folders at all. shift-reload, restarting the browser, and logging out do not clear the problem.

This is on Firefox Quantum 69.0.1 64-bit on Ubuntu 18.04.

**Comment by gtandersen** [comment] 2019-09-28 05:27
@deutrino I'm not able to reproduce this problem with Firefox 69.0.1. Did the folder name include any special characters that might have caused problems, perhaps?

**Comment by tadzik** [comment] 2019-09-28 09:08
Possibly @deutrino is the second victim (after me :P) of the ordering bug: https://github.com/runbox/runbox7/pull/286

**Comment by MishimaHaruna** [comment] 2019-10-03 14:14
I ran into the same problem when I tried to add folders from Runbox 7 a while ago (and gave up, added some of them from Runbox 6 and some of them via IMAP). I'm not sure if it can be relevant, but in my case the folders are nested in a structure equivalent to the following:

```
(root)
|- Drafts
|- Inbox
|- Sent
|- Spam
|- Trash
`- Archive
    |- Foo1
    |- Foo2
    |- Foo3
    |   |- Bar1
    |   `- Bar2
    |- Foo4
    |   |- Bar3
    |   | ...
    |   `- Bar16
    `- Foo5
```

**Comment by petersalomonsen** [comment] 2019-10-03 17:24
@gtandersen @tadzik I think it might be needed with some server-side functionality that sorts the priority field ( as can be seen in https://runbox.com/rest/v1/email_folder/list ) for all folders, when adding a new folder. So that a new folder should not be added with priority 0 as it seems to be now, but with the correct index depending on where in the hierarchy it's added (and folders below it needs to increase one in priority).

**Comment by deutrino** [comment] 2019-10-12 21:19
My folders are still not visible in Runbox 7. I am not sure how to get them back.

I believe the folder had a ```-``` character in its name.

**Comment by tadzik** [comment] 2019-10-15 00:24
Can you see if https://runbox.com/app-beta/ shows your folders correctly?

Note that this is a preview version, and not a public release:
some stuff may be broken, some stuff may be half-done or work incorrectly.
It's only intended for a public triage of bugfixes like this one.

**Comment by tadzik** [comment] 2019-11-25 08:25
This was (hopefully) fixed with other folderlist changes in recent weeks.

Please reopen this if you're still having problems.

**Closed by tadzik** 2019-11-25 08:25 UTC
