### ISSUE TITLE
Missing message list when message pane is open

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#1087] opened 2021-09-28 17:09 UTC
From a customer:

In Microsoft Edge browser running in Windows 10, using Runbox 7 the listing of emails in the inbox sometimes only shows the date and not the subject line.

The issue does not show in Runbox 6 on the same computer and same browser and doesn't happen in Runbox 7 with the Chrome browser.

Changing to the Sent folder, then back to the Inbox, the subject, etc does appear for a second or so, then disappears.

If the preview pane is closed, the columns show without issue.

**Comment by runboxdave** [comment] 2021-09-30 09:37
Screenshot uploaded with permission from the customer.
![missingmessagelist](https://user-images.githubusercontent.com/5822260/135427900-e92463fc-0c9e-4277-a7a7-5b6cba18ecbe.png)

**Comment by gtandersen** [comment] 2021-11-02 13:48
Is anyone else able to reproduce this on Wint10 with Edge?

**Comment by piratefinn** [comment] 2022-01-05 12:14
@runboxdave Was there any followup on this? Im strongly suspecting that quite frankly, because the size of the columns can be dragged horizontally, they have simply had it dragged too far to one side and didn't drag it back or such. My assumption for this is because when i swap back and forth it "blinks" a different column length but otherwise practically instantly corrects itself (you'll see this if you swap between Sent and Inbox).

**Comment by gtandersen** [comment] 2022-01-26 17:54
Not able to reproduce this with Edge 97.0.1072.69 on Windows 10 with or without local index; closing issue.

**Closed by gtandersen** 2022-01-26 17:54 UTC
Labels: bug, P-urgent, status-can't reproduce
