### ISSUE TITLE
mail: reply includes meta text "SafeValue ..."

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#1035] opened 2021-06-21 16:23 UTC
When answering using rb7, since recently (or i have seen in only recently?) a non-sense text (`SafeValue must use [property]=binding:`) is added between the header and the body of the answered message.

**Comment by castaway** [comment] 2021-06-24 10:38
Thanks, several folks noticed it, it was the result of an update to make HTML emails load faster. It's been rolled back and a new & improved one is in the works.

**Comment by castaway** [comment] 2021-06-24 10:56
Duplicate of #1020

**Closed by castaway** 2021-06-24 10:56 UTC
