### ISSUE TITLE
Check box selection not updating when message list changes

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#962] opened 2021-04-18 21:24 UTC
If one or more messages' check boxes are selected and the list in the meantime is updated with new messages, the selection is not updated to reflect the new list (using local index).

This means that it's easy to perform actions on the wrong messages, because a list of 2 messages with a selection such as this:

- [X] Foo
- [ ] Bar

...will look like this if a new message arrives before an action is performed:

- [X] Baz
- [ ] Foo
- [ ] Bar

**Comment by castaway** [comment] 2021-04-20 10:42
Duplicate of #914

**Closed by castaway** 2021-04-20 10:42 UTC
Labels: P-urgent, bug

**Comment by gtandersen** [comment] 2021-04-21 06:49
> Duplicate of #914

Indeed it was! Good find. :)
