### ISSUE TITLE
If cookies are not enabled (safari private mode) login does not work

### ISSUE THREAD

**Issue by fpietrosanti** [runbox/runbox7#619] opened 2020-05-31 07:53 UTC
If cookies are not enabled (safari private mode) login does not work and there's no error or user feedback being provided.

I switched to runbox6 and it gave me the proper error, on why login was not working:
"Web cookies are required. Please enable web cookies in your browser. Read more: https://help.runbox.com/cookies/"

**Comment by gtandersen** [comment] 2022-10-06 20:20
Thanks for testing @piratefinn -- I can't reproduce this either in Safari private mode on macOS.

Closing issue.

**Closed by gtandersen** 2022-10-06 20:20 UTC
Labels: bug, P-urgent
