### ISSUE TITLE
#Payments: Stripe payments hang when users attempt to reopen status 4 accounts

### ISSUE THREAD

**Issue by perigrin** [runbox/runbox7#1409] opened 2023-04-17 22:35 UTC
https://gitlab.runbox.com/runbox/payment/-/issues/23

**Comment by castaway** [comment] 2024-04-15 10:59
Tested together with @runboxdave - we can't reproduce this with manual testing (setting an account to status=4 deliberately). However we discovered a related issue, created as #1554

**Comment by gtandersen** [comment] 2024-05-07 15:20
Closing issue since it isn't reproducible.

**Closed by gtandersen** 2024-05-07 15:20 UTC
Labels: bug, P2-high
