### ISSUE TITLE
Issues when message list is narrow

### ISSUE THREAD

**Issue by vertigo220** [runbox/runbox7#549] opened 2020-04-20 04:21 UTC
When the message list is resized to make it very narrow, which I prefer, it switches from showing the time for the current day's messages to showing the date, and despite still having the size heading, the sizes are not displayed. Also, I had one instance of opening a message while in this narrow view and the message remained bolded, appearing unread despite being read at this point (this may be related to issue #448).

**Comment by gtandersen** [comment] 2020-05-27 00:22
@vertigo220 I'm not able to reproduce this -- can you post a screenshot (not showing any personal details)?

**Comment by vertigo220** [comment] 2020-05-27 00:44
The accounts I set up previously to test it out are expired, so I can't log in to do this. I tried creating another account but it says "Error: There was a problem setting up your account. Please contact Runbox Support to complete the process." (doesn't give any indication of what the problem is, otherwise I would see if I could get it working). Also, I'm not sure if you're having trouble reproducing the main issue or the second problem I mentioned, but if it's the latter, as I recall--and based on how I worded it--it was an intermittent problem, so it's possible reproducing it could be quite difficult.

**Comment by gtandersen** [comment] 2023-06-27 09:23
Neither problem is currently reproducible; closing issue.

**Closed by gtandersen** 2023-06-27 09:23 UTC
