### ISSUE TITLE
Keep message selections when closing preview pane

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#10] opened 2018-12-15 00:24 UTC
"Closing message pane deselects multiple selection in message list - selection should persist."

Ref: https://forum.runbox.com/newreply.php?tid=56, https://community.runbox.com/t/selecting-scrolling-issues/670.

**Comment by kotecky** [comment] 2020-02-05 14:15
And similarly: previewing a message should not deselect the selection either. (Typically used to verify whether a given message should or should not be part of a selection that is being made.)

**Comment by vertigo220** [comment] 2020-04-19 23:04
It's disappointing to see this issue, which should be _relatively_ simple to fix and is, IMO, quite serious (imagine going through and selecting a bunch of emails, then closing the preview pane and losing all your selections; I would be extremely upset), has been around for almost 1.5 years and hasn't been fixed yet.

Furthermore, this issue is even more serious due to issue #11, since the user is forced to close the pane in order to gain access to those functions.

**Comment by vertigo220** [comment] 2020-05-28 20:33
There has been some discussion on this in #542, which I've closed since it's along the same lines as this and it's best to just reference it and carry over the important parts into this issue. That issue started by seeing this behavior from a different angle, essentially in reverse. Instead of (well, in addition to really) finding it problematic that message selections are removed when the preview pane closes, I thought it would be nice if unchecking an email would close it. However, as @tadzik pointed out, the current design is contradictory and leads to unexpected behavior, and it's probably best to just disconnect the two functions (checking/unchecking and opening/closing messages) so one has nothing to do with the other.

There's also some discussion about how to handle multiple message selections:

"with multiple emails. We could display a summary of the selected ones on the email preview pane, possibly with some message actions: that would be even handy."

and

"each checked email could show as a narrow strip with just the header info (from/to/subject/date) in the preview pane, making it easy to see what emails are selected as you scroll through the folder. Sort of like how Fastmail does it but not stacked."

@tadzik brought up concerns about this showing and causing disruption if the user doesn't normally use the preview pane, to which I would say there could simply be a separate option to enable this, which would automatically be enabled if the preview pane is in use and automatically disabled with the ability to enable it if not.

**Comment by castaway** [comment] 2020-05-29 08:44
Re: summaries of whats selected, does turning on the "Inline previews" help?

**Comment by vertigo220** [comment] 2020-05-29 12:26
I think you're misunderstanding what we mean by that. I use inline previews, but that's different from what we're talking about. What we're saying is that when selecting multiple emails, brief info on the selected emails, such as the header info, should be shown in the preview pane to show which emails are selected. So, for example, if you have a few hundred messages in a folder and select one or two on the first page, scroll down a page or two, select a couple more, scroll down some more, select some more, and so on, you can see which one's you've selected even though they're no longer visible in the message list since they've been scrolled out of view, because they'll be shown on the right. In fact, it could be as simple as showing them on the right, in the preview pane, just as they are shown in the left, the main message list, when they're selected. In other words, when selecting messages, the preview pane could be turned into a message pane that acts like GitHub's issues search where the filter would be is:current_folder is:selected.

**Comment by castaway** [comment] 2020-06-29 15:38
The "bug" part of this is now done, see #651 for the preview pane part

**Closed** 2020-06-29 15:39 UTC
Labels: P-medium, bug
