### ISSUE TITLE
Message actions do not work after stopping and restarting index synchronization

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#1191] opened 2022-01-24 20:45 UTC
**Describe the bug**
After stopping and restarting index synchronization, further synchronization of the index fails and the console says:

`Search index deleted in the middle of indexing process`

**To Reproduce**
1. Go to https://runbox.com/app and ensure index sync is enabled
2. Click to stop index synchronization
3. Click to start index synchronization
4. Observe that no message actions (moving to folders etc) work, and the above error message

**Expected behavior**
Index synchronization and message actions should work normally after stopping and restarting index synchronization.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
The issue might be resolved by forcing a reload of the app after index synchronization is stopped.

**Comment by gtandersen** [comment] 2022-01-25 09:51
Duplicate of #1190, but leaving it open as it contains some additional information.

**Comment by castaway** [comment] 2022-01-26 16:10
Duplicate of #1190 (closing as we can still read both)

**Closed by castaway** 2022-01-26 16:10 UTC
Labels: bug, P-urgent
