### ISSUE TITLE
Mail: check all/none does not select all

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#641] opened 2020-06-16 07:53 UTC
When clicking on the "check all/none" button at the top of an mailbox, not all messages are selected. Typically only the currently displayed messages are selected and those below the current viewport are not: 

![runbox_selection_2](https://user-images.githubusercontent.com/2297444/84746840-ce673380-afb6-11ea-909f-cbe283e2ec5b.png)

Other times it results in a random selection: 

![runbox_selection_1](https://user-images.githubusercontent.com/2297444/84747157-33bb2480-afb7-11ea-83c3-5188f17aca4e.png)

Normal behaviour: All messages in a folder should be selected. (Or is this behaviour by design?)

**Comment by gtandersen** [comment] 2020-07-08 09:36
@kotecky Thanks; however this appears to be a duplicate of #61?

I have bumped the priority of that issue now.

**Comment by kotecky** [comment] 2020-07-08 12:36
Not really. Selection of all images can be regarded as a meaningful feature. Instead of inadvertently emptying a mailbox, only the visible messages would be gone, for example. On the second screenshot above, the selection seems to be a bit more random.

**Comment by gtandersen** [comment] 2020-07-10 14:29
> Selection of all images can be regarded as a meaningful feature.

Can you expand a bit more on what you mean here?

The purpose of #61 is to allow for the selection of only **visible message** or **all messages**. 

Note that if clicking the "check all" option while performing a search and then removing one ore more criteria, the selected messages may appear random because some messages that did not match the search might be shown as well.

**Comment by kotecky** [comment] 2020-09-18 07:11
Images > messages. Typo, sorry.

**Comment by gtandersen** [comment] 2021-04-27 12:56
@kotecky Selection of all (including invisible) messages has been implemented.

Are you still seeing random selections as in the screenshot?

**Comment by kotecky** [comment] 2021-04-27 16:44
Yes. It can be reproduced either by a search followed by a selection (search, select, cancel search, select) - the first page (visible messages) get selected but those from the earlier cancelled search (that are now below) are still selected. Expected behaviour of "advanced selection"?

Or by a selection followed by scrolling and another selection. This is kind of OK - one can increase the number of selected messages but when only selected messages are visible, a new click on the select button deselects and the selection process start to be fuzzy...

**Comment by gtandersen** [comment] 2021-05-07 09:31
Thanks for the additional details.

It's possible this will be fixed by https://github.com/runbox/runbox7/pull/920 (when deployed).

**Comment by castaway** [comment] 2023-03-13 16:20
Is this still an issue?

**Comment by kotecky** [comment] 2023-03-14 13:18
As of today when clicking on the "check all/none" button at the top (Win10, FF) only the currently displayed messages are selected. State is the same as at submission.

**Comment by gtandersen** [comment] 2023-03-27 09:45
@kotecky Does this occur even after clicking and holding the check-all box, and then selecting "All rows"?
<img width="161" alt="All rows" src="https://user-images.githubusercontent.com/1620058/227905486-4543bca6-11c4-4e8d-810b-99114373f21d.png">

**Comment by kotecky** [comment] 2023-03-27 11:04
@gtandersen Oh, that works - despite the hover popup i did not remark that feature. Now i know.

**Comment by gtandersen** [comment] 2023-03-27 23:11
@kotecky Excellent!

Closing issue.

**Closed by gtandersen** 2023-03-27 23:11 UTC
