### ISSUE TITLE
checkboxes toggled in folder with message open are cleared upon message close

### ISSUE THREAD

**Issue by deutrino** [runbox/runbox7#303] opened 2019-09-19 15:25 UTC
STEPS TO REPRODUCE

1. Open a folder.
1. Open a message.
1. Toggle some checkboxes in the folder with the message open.
1. Close the message.

EXPECTED RESULT

The checkboxes' toggle state is not changed.

ACTUAL RESULT

The toggled checkboxes are cleared.

**Comment by gtandersen** [comment] 2019-09-19 19:26
@deutrino This seems to be a duplicate of #10.

**Comment by tadzik** [comment] 2020-05-27 16:44
Somewhat related to https://github.com/runbox/runbox7/issues/542.

**Comment by vertigo220** [comment] 2020-05-28 20:03
Agree this is a duplicate of #10.

**Comment by gtandersen** [comment] 2023-06-27 12:21
This is no longer reproducible; closing issue.

**Closed by gtandersen** 2023-06-27 12:21 UTC
