### ISSUE TITLE
"Undefined" ipo header when replying

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#234] opened 2019-08-15 09:32 UTC
When replying to a message, the word "undefined" is placed in place of the "reply header" (from, time, to, subject). Spotted once, could not reproduce even with the same message, message being replied-to has all fields (from and to email, subject not blank).

> ![image](https://user-images.githubusercontent.com/2297444/63085849-ce3d7800-bf4e-11e9-940c-1726d9311e6d.png)

**Comment by gtandersen** [comment] 2019-08-28 16:39
Not able to reproduce this. Closing issue; reopen if it occurs again.

**Comment by kotecky** [comment] 2021-11-18 07:25
Since recently i get it every time, irrespective of the sender's client (desktop, phone app, automated email). HTML email seems to be a precondition. 

( Runbox 7 build time: 2021-11-15T13:08:33.650Z )

**Comment by gtandersen** [comment] 2021-11-28 00:02
Yes, I see this too now on HTML messages.

@kvviecien Could this be related to https://github.com/runbox/runbox7/pull/1120, or is it independent?

**Comment by kvviecien** [comment] 2021-11-29 14:37
@gtandersen There is a possibility my fix could break after fixing the headers for recent Sentry issues, because that's the same part of the code. I will look into it again.

**Comment by gtandersen** [comment] 2021-12-26 17:06
This appears to be much better but can still be reproduced with some messages, e.g. with https://runbox.com/app/#Inbox:12205016 in the test account.

**Comment by kotecky** [comment] 2022-03-01 09:27
Still there, confirmed.

**Comment by kotecky** [comment] 2022-03-11 08:16
Is it not persistent when answering to more than one recipient?

**Comment by gtandersen** [comment] 2022-03-12 20:11
@kotecky Thanks for the updates. 

Do you mean that the error occurs when replying to one recipient but not when replying to more than one recipient?

**Comment by kotecky** [comment] 2022-03-12 23:02
@gtandersen, that's what I meant, but dud not try. A hypothesis to be tested.

**Comment by gtandersen** [comment] 2022-10-26 12:36
Not reproducible with the above example message.

Closing issue; reopen if it occurs again.

**Comment by kotecky** [comment] 2022-11-08 23:29
@gtandersen To be reopened as it is currently happening again.

**Comment by kotecky** [comment] 2023-01-12 21:22
> @gtandersen To be reopened as it is currently happening again.
@gtandersen Issue still there.

**Comment by gtandersen** [comment] 2023-01-20 00:04
@kotecky Issue reopened.

Would you be able to provide an example message (your Runbox username and the message's ID from the browser URL) via Runbox Support?

Thanks!

**Comment by kotecky** [comment] 2023-01-23 12:55
@gtandersen 
Answering to the support via a ticket.

**Comment by kotecky** [comment] 2023-01-23 12:57
But i have the impression that it has to do with the state (slow XRH or something) rather than the message itself - sometimes it kicks in ("undefined") for one message but not when trying the second time for the same message. A third attempt would be again "successful" in reproducing.

**Comment by gtandersen** [comment] 2023-03-31 22:42
@kotecky Thanks for the additional details. This then appears to be performance related and not caused by a bug per se.

**Closed** 2023-05-03 09:47 UTC
Labels: bug, P-urgent
