### ISSUE TITLE
tinyMCE hijacks the right-click context menu and prevents spellchecking

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#769] opened 2020-09-18 06:26 UTC
TinyMCE hijacks the right-click context menu. It concerns the rich text formatting (words not underlined, right-click context menu not accessible which drives me mad when using many MS products):

![tinymce_editor_wysiwyg](https://user-images.githubusercontent.com/2297444/93563633-95a97280-f988-11ea-858a-905f434bb7ea.png)

In non-HTML text the spellchecker (and the right-click context menu) work as expected:

![tinymce_editor_simple-text](https://user-images.githubusercontent.com/2297444/93563656-9e9a4400-f988-11ea-91d0-a0d5e1ebf2c7.png)

And on phones this prevents the copy-paste mechanism, which is very very disturbing.

**Comment by gtandersen** [comment] 2020-09-20 05:54
The TinyMCE right-click context menu can probably be disabled in HTML mode since the user can instead click the link icon in the toolbar.

**Comment by kotecky** [comment] 2020-09-22 12:25
Using the last build (2020-09-21) the right-click is not hijacked any more, this is great. But the link icons is missing in the ribbon: 

![image](https://user-images.githubusercontent.com/2297444/93880591-0381d100-fcde-11ea-94d8-69106cba47d6.png)

As we speak, lists (bulleted and ordered lists) and underlined text are missing. (And if we could, why not to have the checklist ![image](https://user-images.githubusercontent.com/2297444/93881154-d5e95780-fcde-11ea-90f1-555c6d322667.png) for to-do email discussions and tables?)

**Comment by kotecky** [comment] 2020-09-23 06:36
To my surprise, the right-click hijack is back in, on the same computer, in the same browser, just a day later.

**Comment by ConnectGrid** [comment] 2020-10-30 05:28
Could this TinyMCE configuration be the culprit/solution?

https://www.tiny.cloud/docs/general-configuration-guide/spell-checking/#browser-basedspellchecking

**Comment by kotecky** [comment] 2021-01-26 13:07
Contrary to the earlier state, today (build time: 2021-01-23T13:26:43.671Z) the spellchecking works FF under Win10.
I do not know whether it did or did not work in Chrome under Win10 earlier, nonetheless today it works too.

**Comment by kotecky** [comment] 2021-02-06 21:24
This issue seems to be gone since ~ 14 days (a very rough estimate). 

Also, this seems to be a duplicate of issue https://github.com/runbox/runbox7/issues/622.

**Comment by gtandersen** [comment] 2021-04-27 10:24
Not able to reproduce this issue either; closing issue.

@kotecky I've added your toolbar suggestions to this new issue: https://github.com/runbox/runbox7/issues/969

**Closed by gtandersen** 2021-04-27 10:24 UTC
Labels: P-medium, enhancement
