### ISSUE TITLE
App hangs in some networks

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#483] opened 2020-03-04 09:48 UTC
Sometimes, not always - I believe that it occurs only in our network at work - after opening the mail app, the email list is not updated and the folder list remains empty. Console shows: 

![image](https://user-images.githubusercontent.com/2297444/75864939-0e891880-5e03-11ea-99f7-c3213174a966.png)

The app gets back on rails immediately after opening one of the URLs related to the errors above in a tab: the messages sync and the folders populate. (When doing so, the proxy does not require an identification.)

**Comment by gtandersen** [comment] 2020-03-11 06:27
Thanks for reporting this, @kotecky.

I have noticed this issue under some circumstances as well, but not found any specific patterns as to the cause.

@tadzik and @hernan604, could this be caused by a timeout on the REST API, or something else?

**Comment by tadzik** [comment] 2020-03-31 13:26
Looks like the proxy is to blame here, and there may not be anything we can do: if the proxy gives us the 504 then there's nothing we can do. It is somewhat curious as to why clicking the links fixes it though. Does the proxy somehow pick up the fact that it's the user that triggered something manually, rather than it happening in the background by itself?

Here's an experiment: when this happens, does it help if you hard-refresh the page (ctrl+shift+r or the equivalent in your browser)? That should redownload all the runbox7 assets, and maybe trick your proxy into thinking that you're doing this consciously?

**Comment by kotecky** [comment] 2020-03-31 17:17
Agree. Not being at work at the moment (and for some more time), I can't test. As far as I remember, curiously, a refresh et ors not help.

**Comment by gtandersen** [comment] 2020-06-04 13:42
Another symptom of this that could be related is that some message actions (e.g. moving messages to a folder) hangs indefinitely when using the app on a mobile/4G network (with excellent connection).

**Comment by kotecky** [comment] 2020-10-28 15:19
Another symptom: the message list (inbox) does not update until the moment when the web developer console (in FF, Win 10), tab Network is opened. Then the messages start to be pulled. Anything to do with the fact that the checkbox Disable cache is ticked? False path?

**Comment by gtandersen** [comment] 2020-10-28 17:47
Interesting find @kotecky -- could this be a clue, @tadzik?

**Comment by kotecky** [comment] 2021-01-27 10:17
Another hint: some requests (typically this one: https://runbox.com/mail/download_xapian_index?exists=check) is not always successful, as displayed in the developer console. If I submit the request manually in another tab, it loads correctly. If the runbox app is reloaded after that, it does not hick up and the app loads correctly.

**Comment by kotecky** [comment] 2021-01-27 10:18
Oh, this was a mis-click, i did not mean to close the request. Could you please reopen it?

**Comment by kotecky** [comment] 2021-01-27 12:36
OK, this might be closer: it looks like the requests that go through are all the HTTP**S** ones, and all the HTTP requests are left hanging. No matter what, the xapian index should be pulled thru HTTPS. 

![image](https://user-images.githubusercontent.com/2297444/105991459-14838a00-60a4-11eb-8dc2-0c41b9b02538.png)
![image](https://user-images.githubusercontent.com/2297444/105991472-1a796b00-60a4-11eb-80a9-18a8500acea5.png)

**Comment by tadzik** [comment] 2021-01-27 12:43
All the requests are performed over HTTPS, be it assets, API endpoints or index downloads. I assume the padlock is just not showing up because the requests didn't actually go through – but just in case, can you check the individual requests and make sure that that's true?

**Comment by tadzik** [comment] 2021-01-27 15:46
I'm pretty sure that your browser is showing them as HTTP because they
didn't go through – on my own browser I see that the padlocks don't
appear until the request completes. Like I said, all requests that
runbox7 performs are done over https.

**Comment by kotecky** [comment] 2021-01-27 16:16
Oh, you are right. My bad  - i was assuming to early...

**Comment by kotecky** [comment] 2021-01-29 15:35
> make sure that that's true?

Yes, confirmed.

**Comment by gtandersen** [comment] 2021-09-22 20:35
Is this still occurring @kotecky?

**Comment by kotecky** [comment] 2021-09-23 06:12
No, it does not happen any more @gtandersen. (Testing possibilities limited - it was happening only in one network.)

**Comment by gtandersen** [comment] 2021-09-25 17:29
I haven't seen this problem either for a long time; closing issue.

**Closed by gtandersen** 2021-09-25 17:29 UTC
Labels: bug, P-urgent
