### ISSUE TITLE
GMT time displayed in "sent" folder list as opposed to the timezone time on the message

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#1160] opened 2022-01-03 12:19 UTC
Email (emails?) in the list of the sent folder have the sent time in GMT ipo the timezone time as in the message itself. It is expected that the timezone time is displayed everywhere. 

I remarked it today, it could have been an older issue. 

List: 
![image](https://user-images.githubusercontent.com/2297444/147929284-f36cf920-fe94-49b8-83b7-3dd8095d7e96.png)

Message: 
![image](https://user-images.githubusercontent.com/2297444/147929402-fa6a6417-0d66-4935-950f-8f28eae7cc92.png)

Witnessed in Runbox 7 build time: 2022-01-03T11:16:53.289Z, under Win10 FF.

**Comment by piratefinn** [comment] 2022-10-06 12:33
This appears to have been fixed with the changes made in #1239 and am unable to reproduce this bug on Win10 FF or Chrome with the index both enabled and disabled.

**Closed by piratefinn** 2022-10-06 12:33 UTC
Labels: bug, P-urgent, status-can't reproduce
