### ISSUE TITLE
Moving preview/message list divider shows strange behaviour (won't move right, only left)

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#1023] opened 2021-06-15 16:53 UTC
When a HTML message is open and you try to drag the divider between the preview window and the message list to the right it won't move. 

After one or more attempts the interface then gets stuck in a state where even without clicking all that happens is as you move the mouse the divider will go left, but never go right. That's until you move the mouse out of the HTML area to the header of the email when suddenly the interface is still stuck without clicking but now you can move left and right. If you then click the interface returns to normal.

**Comment by piratefinn** [comment] 2021-09-10 12:42
Narrowing down the issue: After some testing poking around with this, I've noticed that if you move the box **above** the "This HTML has been sanitized for security, it grabs mouse focus and without holding down left click and allows it to be moved left and right and needs to be clicked away from the interface to allow free mouse control without moving it. As such while the sanitised inner HTML frame in vertical occupation causes issues, once you try to change the horizontal amount of the box vertically above the warning/html content, it works as intended.

**Comment by gtandersen** [comment] 2022-06-01 16:24
Good find @piratefinn, although I think you might have meant "move the cursor" instead of "move the box" as that would correctly describe what I am experiencing currently.

**Comment by gtandersen** [comment] 2023-10-10 10:03
No longer able to reproduce this; closing.

**Closed by gtandersen** 2023-10-10 10:03 UTC
Labels: bug, P-high
